services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - database-data:/app/database
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:UN1wmEoPm7F7cxaQ6ZNxqhwTEJo4B7YUPy0TNBbFYMk=
      - DB_CONNECTION=sqlite

volumes:
  database-data:
